layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      - personal-website

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: gabor.somogyi.790
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: gabor-somogyi
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  github: [metadata]

topics:
  - name: Apache Spark
    web_url: https://spark.apache.org/
    image_url: https://raw.githubusercontent.com/apache/spark/master/docs/img/spark-logo-hd.png 

  - name: Apache Kafka
    web_url: https://kafka.apache.org/
    image_url: https://svn.apache.org/repos/asf/kafka/site/logos/kafka-logo-tall.png

  - name: Apache Flink
    web_url: https://flink.apache.org/
    image_url: https://flink.apache.org/img/flink-header-logo.svg

  - name: Scala
    web_url: https://www.scala-lang.org/
    image_url: https://raw.githubusercontent.com/scala/scala/2.13.x/src/manual/scala/tools/docutil/resources/images/scala_logo.png

  - name: Java
    web_url: https://www.java.com/en/
    image_url: https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/300px-Java_programming_language_logo.svg.png
